spring.application.name=emill

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chandrashekhardama18@gmail.com
spring.mail.password=dvph xrpu auew zvas
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File paths for the email sending process
#email.excel.file.path=D:/personal/my docs/Hr_mail_list/Company_Wise_HR_Contacts_L2.xlsx
email.excel.file.path=D:/personal/my docs/Hr_mail_list/contacts.xlsx
#email.source.flag=excel
email.attachment.file.path=D:/personal/my docs/Hr_mail_list/Java_Developer.pdf
#email.template.file.path=D:/personal/my docs/Hr_mail_list/templete/email_template.txt
email.source.flag=txt
email.txt.file.path=D:/personal/my docs/Hr_mail_list/email_searched.txt
#email.txt.file.path=D:/personal/my docs/Hr_mail_list/email_searched_test.txt
email.template.file.path=D:/personal/my docs/Hr_mail_list/templete/noname_email_template.txt

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG

# Sender email address
email.sender.address=chandrashekhardama1999@gmail.com